language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: ideas-from-nodejs
  api_key:
    secure: LHWn3/qSYKwlSWPwFtxoLM++K8ObKFpyWR2Qg0WmIp6upjgDbwTLVVBObUZ1v5D7KQyJDzIFiVNGHJSfRMIgkkbcMzd7RLtmDVk+YNz+vdtHJ80+wObFDnV1lVQgCAvtBt9kzC4oMV43ot9Ao7gxE0PMk2v6CeDCXsxC6TjuoXsdbMu9KA/EkLZTVL9HdADCF01PcwTy7oKDbaQyJWqYypl+baoI43/tElFumEDDweRtayapCnBMW+EhWdudFPOiVeFb4dmnnfpP8IyrZiwk2VAzQhEVAHDxJYCQEKsogmyn75XViRb5lAsRmPGKH//+/SvlnsOZXfI3Q5BMbZfjulnlXJsT32r8+U1kuLRRxtxkpOrwr7MvWprT+GUakSthWV32vHbzPzCfKJlXyX5OCZ+XO8G3qS8OyQ9Tlr0ewr975Y9oAWNZKHjTOKlNa5d/x7u6lVK3ASdsFCMkMmO0AjTqXfZI18Rc28k2bdCkTBTzMeA65Nk0Mdw05n2NRgoNPYxvKmKQGzP6XFXwKPOS+HUbkISFtTj5OHEDx8z0kH0GEwRpCboDtgiDd0qDbCGjRk8UQXVcXj4gf5DK9xJ7qJWGdhp0V6jejBOTzdfRZ8+s2GIOAd9sHy2At8zlLYgjoMawHOIysFk6E6vaOPNStVgac6DIH4trOq0VmYLayCE=
  