language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: ideas-from-nodejs
  api_key:
    secure: WlzCv86LQvYmCeyXCrBkmd0JLr5FrMImJ9hPAs1tQ2Kc5Aj0iWIee4DfGYsLCEz/cGMSnzdawDMSiZS29nEewtPiW4uOvEVti7LImlKTZxEqpIiarqgqF6nGcnXmSibjcCpxCd7drHuFjR1d7d/Y2ZZvsAYDYGW5L4p377i1rNUquSRwwpV65rqL/C1n93J+qhlrdaVaxGTsNkRRrdDdY8qS9nSQIrMOj+ZkfcTeN5tb76Z3HwWyup0IxS0+jceEUDEAT1PNgx5rdm73K6EQYz3KZ91wZkzhghygO7PGdB6SD/ca5eYSA4VwG/PX+zFoihWl8kLch+3vNyFxIKrpwe/W9KxXD0RRIB2WArnOxG3OB7ijTya5x3kTyINY0REjYc9/XXTMeQ1O6kdx65C5iVfcXBwbt1LSXNXu/C5VFnqMtgXaQhPQYYVSffuEzl0ZukVIjdRwJlIszDtaDu6n/YGBc9IPYKpRkH/eWgkjpT/hMo9nCkXNUsAFLgIH8HsJrut2FJx5xKgOr0bGmm+eNu33K158ZA8akebzBsER3pc7TPfBeE1h05e3p694BjYhJZha5ifwY2xtXFU+Md3ps+ebkl1ih5mIcGYWciRnqxMS9aMFC+fBiwOqRme2jetqfBCxtW50wG30WynEc2ZF5gO466VVXnFK3O7fz0q/Rvs=
